include:
  - ../infra/compose.yml

services:
  # Media server
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:12.1ubu2604-ls51
    container_name: jellyfin
    ports:
      - "8096:8096/tcp"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./config:/config
      - /mnt/external/Jellyfin:/media
    devices:
      - /dev/dri:/dev/dri # Use for Intel QuickSync
    restart: unless-stopped
    profiles: [media, media-slim]

  # VPN
  gluetun:
    image: qmcgaw/gluetun:v3.41.3
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - "8080:8080/tcp" # qbittorrent web interface
      - "9696:9696/tcp" # prowlarr
    volumes:
      - ./gluetun:/gluetun
    environment:
      - FIREWALL_VPN_INPUT_PORTS=${FIREWALL_VPN_INPUT_PORTS}
    env_file:
      - ./gluetun/.env
    healthcheck:
      test: ping -c 1 www.google.com || exit 1
      interval: 20s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    profiles: [media]

  # Media discovery
  seerr:
    image: ghcr.io/seerr-team/seerr:v3.5.0
    container_name: seerr
    environment:
      - TZ=${TZ}
    volumes:
      - ./seerr:/app/config
    ports:
      - 80:5055
    depends_on:
      jellyfin:
        condition: service_started
        restart: true
      radarr:
        condition: service_started
        restart: true
      sonarr:
        condition: service_started
        restart: true
    restart: unless-stopped
    profiles: [media]

  # Torrent client
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:5.2.4
    container_name: qbittorrent
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=8080 # must match "qbittorrent web interface" port number in gluetun's service above
      - TORRENTING_PORT=${FIREWALL_VPN_INPUT_PORTS} # airvpn forwarded port, pulled from .env
    volumes:
      - ./qbittorrent:/config
      - ./data:/data
      - /mnt/external/Jellyfin:/media
    depends_on:
      gluetun:
        condition: service_healthy
        restart: true
    network_mode: service:gluetun
    restart: unless-stopped
    profiles: [media]

  # Central indexer
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:2.6.5
    container_name: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./prowlarr:/config
    depends_on:
      gluetun:
        condition: service_healthy
        restart: true
    network_mode: service:gluetun
    restart: unless-stopped
    profiles: [media]

  # TV shows
  sonarr:
    image: lscr.io/linuxserver/sonarr:4.0.20
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./sonarr:/config
      - ./data:/data
      - /mnt/external/Jellyfin/Series:/series
    ports:
      - 8989:8989
    depends_on:
      qbittorrent:
        condition: service_started
        restart: true
    restart: unless-stopped
    profiles: [media]

  # Movies
  radarr:
    image: lscr.io/linuxserver/radarr:6.4.4
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./radarr:/config
      - ./data:/data
      - /mnt/external/Jellyfin/Movies:/movies
    ports:
      - 7878:7878
    depends_on:
      qbittorrent:
        condition: service_started
        restart: true
    restart: unless-stopped
    profiles: [media]
